// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/app-nav-concepts/Briefing.tsx": () => import("../components/mockups/app-nav-concepts/Briefing.tsx"),
  "./components/mockups/app-nav-concepts/Cruscotto.tsx": () => import("../components/mockups/app-nav-concepts/Cruscotto.tsx"),
  "./components/mockups/app-nav-concepts/Giornale.tsx": () => import("../components/mockups/app-nav-concepts/Giornale.tsx"),
  "./components/mockups/app-nav-concepts/Presenze.tsx": () => import("../components/mockups/app-nav-concepts/Presenze.tsx"),
  "./components/mockups/dashboard-layouts/FeedPriorita.tsx": () => import("../components/mockups/dashboard-layouts/FeedPriorita.tsx"),
  "./components/mockups/dashboard-layouts/Quadranti.tsx": () => import("../components/mockups/dashboard-layouts/Quadranti.tsx"),
  "./components/mockups/dashboard-layouts/StrisciaCRaffinata.tsx": () => import("../components/mockups/dashboard-layouts/StrisciaCRaffinata.tsx"),
  "./components/mockups/dashboard-layouts/StrisciaCcmando.tsx": () => import("../components/mockups/dashboard-layouts/StrisciaCcmando.tsx"),
  "./components/mockups/dashboard-layouts/StrisciaProfonda.tsx": () => import("../components/mockups/dashboard-layouts/StrisciaProfonda.tsx"),
  "./components/mockups/colocation/CoLocationPills.tsx": () => import("../components/mockups/colocation/CoLocationPills.tsx")
};
